site_name: Developer relations anywhere
repo_url: https://github.com/episod/developer-relations-template/
site_url: https://devrel.realitytechnicians.com/
site_author: Taylor Singletary

nav:
  - 'README': 'index.md'
  - 'Template': 'template.md'

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-N3P13C48TR
