site_name: Developer relations anywhere template
repo_url: https://github.com/episod/developer-relations-template/
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-N3P13C48TR
